package com.cailangrott.peoplemanager.exception;

public class RecursoNaoEncontradoException extends Exception {
    public RecursoNaoEncontradoException() {
        super("Recurso n√£o encontrado!");
    }
}
